# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_clang:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Run code
      run: |
        sudo apt install clang-18 clang-tidy-18 clang-format ninja-build libgtest-dev -y
        export CC=$(which clang-18)
        export CXX=$(which clang++-18)
        git config --global user.email "ci@github.com"
        git config --global user.name "GitHub CI"
        chmod +x initcpp.sh
        sudo cp initcpp.sh /usr/local/bin/initcpp
        sudo initcpp -i
        initcpp testproj

        cd testproj/build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
        ninja
        ./testproj
        ctest

  build_gcc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run code
      run: |
        sudo apt install ninja-build libgtest-dev -y
        git config --global user.email "ci@github.com"
        git config --global user.name "GitHub CI"
        chmod +x initcpp.sh
        sudo cp initcpp.sh /usr/local/bin/initcpp
        sudo initcpp -i
        initcpp testproj

        cd testproj/build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
        ninja
        ./testproj
        ctest
